### PR TITLE
Switch from requirements.txt to pipenv

### LINKED ISSUE #211: Switch from requirements.txt to pipenv
For many years, the standard way to list dependencies in a Python project has been to include a file conventionally named `requirements.txt`, listing Python packages that can be installed with `pip install -r requirements.txt`. That approach has a number of issues, though.

One issue is that, if you want to pin all your dependencies to known-good versions, then all your transitive dependencies need to be listed as well, which makes it hard to tell whether you still need all the same packages once you stop using one of them. This is the usage mode assumed by `pip freeze`, so the existing tooling has really encouraged this problem.

Another challenge is keeping separate requirements for dev vs production. Some projects provide a separate `requirements-dev.txt`, but again, `pip freeze` doesn't know which packages should go in which file, so the tooling makes this difficult.

[Pipenv](https://docs.pipenv.org/) is a relatively new tool that combines pip with virtualenv in a unified way, and solves both of the above issues as well. Direct dependencies are tracked in a new file named `Pipfile`, which can specify general version constraints or declare that all versions of a dependency should work. The equivalent of `pip freeze` gets stored in a separate file, `Pipfile.lock`, that is automatically managed by Pipenv. That way, removing a direct dependency from `Pipfile` allows automatically removing everything else that's no longer needed from `Pipfile.lock`. And the `Pipfile` has separate sections for production and development requirements, as well as allowing you to specify which version(s) of Python your project supports.

Conveniently, the Heroku Python buildpack already supports detecting the presence of a `Pipfile` and using `pipenv` instead of `requirements.txt`, so making this switch doesn't require any changes to how the site gets deployed to Dokku. It only requires some changes to this project's documentation for the process of setting up a development environment.

Pipenv has documentation on [how to switch from an existing `requirements.txt` to a `Pipfile`](https://docs.pipenv.org/basics/#importing-from-requirements-txt). That will leave a messy `Pipfile` that still has the same problems that the original `requirements.txt` had, but from there it's easier to clean it up, or at least to use better practices when adding new dependencies. So I'd suggest to start there:

- `git add` both the `Pipfile` and `Pipfile.lock` that you get from that import process,
- `git rm` the old `requirements.txt`,
- update the documentation to cover using Pipenv instead of `pip install`,
- and put off the rest of the cleanup for later.

I think this will also eliminate the need for #121.

### PR DESCRIPTION
**Pull request by shailysangwan**
Fixes #211

### CODE REVIEW

**Comment by jameysharp** [comment]
I didn't actually receive any notifications so thank you for mentioning your pull request! I keep hoping that someday I will understand how GitHub's notifications work. :sweat:

I need to test this, just to be sure, but first I want to say that this pull request looks excellent. I especially appreciate that you updated the README as well with good instructions.

I may not get around to testing and merging this today, but if I haven't done so in a couple more days please ping me again. Thank you for this contribution!

**Comment by sagesharp** [comment]
Thank you for the pull request @shailysangwan! I'm new to pipenv. How does this impact recording a change in the Python package requirements?

Before, I would run `pip freeze --local > requirements.txt` to change any requirements. What's the new command using pipenv?

This should probably be documented in the README. I know the command to update Python package requirements wasn't documented before, but I would appreciate it if you could document it for others.

**Comment by shailysangwan** [comment]
@sagesharp pipenv is similar to npm in this regard, in how it adds/removes packages from your Pipfile as you install/uninstall them.
I've added the instructions for installing a package, and more can be found in the linked pipenv documentation.

**Comment by shailysangwan** [comment]
@sagesharp pipenv is similar to npm in this regard, in how it adds/removes packages from your Pipfile as you install/uninstall them.
I've just added a commit that specifies this in the README.

**Comment by sagesharp** [comment]
This works for me locally. I updated the README to include instructions on how to install pipenv. I ended up needing to install Linuxbrew instead of Homebrew, so I figured that should be documented.

When I deployed this to the test site, I did see the following error:
```
-----> Installing requirements with latest Pipenv…
       Installing dependencies from Pipfile.lock (611b5c)...
remote: Traceback (most recent call last):
remote:   File "/tmp/buildpacky8nJn/vendor/pip-pop/pip-diff", line 15, in <module>
remote:     from pip.req import parse_requirements
remote: ModuleNotFoundError: No module named 'pip.req'
```
The site seems to work though, so I guess it's not a problem? @jameysharp any comments on this error?

**Comment by sagesharp** [comment]
Thanks @shailysangwan! This is now live on the Outreachy website. :tada:

**Comment by jameysharp** [comment]
@sagesharp The proximate cause of that error message is that Pip version 10 moved the specified function to an internal module (https://stackoverflow.com/a/49867265). I think the Heroku buildpack for Python just hasn't been updated to reflect that change, but as far as I can tell the error is harmless. I've encountered it before when deploying another Python project to my own Dokku and everything seems to work fine.

**Comment by jameysharp** [comment]
Also the issue is known upstream (heroku/heroku-buildpack-python#700) so presumably the problem will go away sooner or later.

**Comment by anukul** [comment]
I've seen it [too](https://github.com/frappe/frappe/issues/5446)!

Apparently pip is not supposed to be used in this manner - https://github.com/pypa/pip/issues/2286

**Comment by shailysangwan** [comment]
@sagesharp Oh, I had installed it using [get-pipenv.py](https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py). I think it's also mentioned in the pipenv documentation, so should we suggest installing Linuxbrew for this purpose?

Sorry for the last comment from another account, I'm using a shared computer.

**Comment by jameysharp** [comment]
I had never heard of Linuxbrew before and I'd hesitate to encourage people to bring in more tools like that.

My first choice would be for people to install pipenv from their Linux distribution's packages if possible.

- I use NixOS which shipped it in the 18.03 release.
- Debian has a pipenv package which has been sitting in the [NEW queue](https://ftp-master.debian.org/new.html) since March for some reason, so it isn't even in the unstable release yet, but it should get there eventually. There's some discussion in the ["Intent To Package" issue for pipenv](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=891486).
- There's an [Ubuntu PPA with various Python packages including pipenv](https://launchpad.net/~pypa/+archive/ubuntu/ppa/+packages), which I suppose might work in Debian too.

I assume other distributions either have already released it or will eventually.

As a second choice I prefer the `pip install --user pipenv` approach documented at https://pipenv.readthedocs.io/en/latest/install/#pragmatic-installation-of-pipenv. The irritating thing about that is it may require fixing your `$PATH`, if your distro hasn't included `~/.local/bin` on the default path. But at least the method for doing so is also documented in the pipenv install directions, more or less.

I don't generally trust installers like `get-pipenv.py` because I don't know what parts of my computer they're going to mess with. In this case, from inspecting the source code I see that it assumes you have Python installed but not pip, so it unpacks a temporary copy of pip in order to install a current version of pip and pipenv. The `get-pip.py` documentation has a scary warning:

> Be cautious if you are using a Python install that is managed by your operating system or another package manager. get-pip.py does not coordinate with those tools, and may leave your system in an inconsistent state.

So for most Linux users I'd suggest the second choice over this option. Anyway, `get-pipenv.py` doesn't do anything to get `$PATH` set correctly, so I think either they expect it to be run as root, which I don't want to encourage, or it has the same difficulties as the second option.

I'm disappointed that installing pipenv is this complicated still and I'm not really sure how to document any of this for people who aren't already comfortable with their chosen Python development environment. I hope this summary of the options helps though.

**Pull request merged**
