### PR TITLE
fix typo. Goverance -> goverNance

### PR DESCRIPTION
**Pull request by yochannah**
Hi! I noticed a small typo on the community application form. Hopefully this will fix it :)

### CODE REVIEW

**Comment by sagesharp** [comment]
Hi @yochannah! Unfortunately that's not enough to fix it. Since you changed a variable name in models.py, you need to create a migration that changes the variable name in the underlying database schema.You can read more about Django models and their underlying database representations [here](https://docs.djangoproject.com/en/1.11/topics/db/models/).

The good news is that migrating a model that has one field name to a new database representation with a new field name is as easy as running two commands. The bad news is it requires you to set up your Django development environment.

You'll need to get your Django environment set up following the instructions in the README. Undo your code changes before you attempt to follow the instructions. After you've gotten past the create superuser step, double check the website works as is by following the "Testing the local website" section.

Then reapply your code changes. Create a migration by running `./manage.py makemigrations && ./manage.py migrate`. You should now have a new migration file in home/migrations/ which you can git commit.

Please double check your migration applies, and the site still works by running the Django server locally, and going to http://localhost:8000/communities/cfp/add/

**Comment by sagesharp** [comment]
You can see a more thorough explanation of what you need to migrate in [this issue](https://github.com/sagesharp/outreachy-django-wagtail/issues/154)

**Comment by yochannah** [comment]
Hah, I suspected that there might be more than meets the eye. Thanks for
the walkthrough, I'll see if I can get to it this weekend!

**Comment by sagesharp** [comment]
Hi @yochannah! I'm closing this open PR, since I haven't heard back from you. I'd love to have you help out if you want to reopen it in the future.

**Pull request closed without merging**
